#
# more information can be found here http://sonata-project.org/bundles/user
#
fos_user:
    db_driver:        orm # can be orm or odm
    firewall_name:    main
    user_class:       Via\Bundle\CoreBundle\Entity\User
    group:
        group_class:  Via\Bundle\CoreBundle\Entity\Group

# Enable Doctrine to map the provided entities
doctrine:
    orm:
        auto_mapping: true
    dbal:
        types:
            json: Sonata\Doctrine\Types\JsonType
sonata_user:
    security_acl:             false
    table:
        user_group:           fos_user_user_group

    impersonating:
        route:                sonata_admin_dashboard
        parameters:           { path: / }

#    google_authenticator:
#        server:               %sonata_user.google_authenticator.server%
#        enabled:              true

    manager_type:             orm
    class:    
        user:                 Via\Bundle\CoreBundle\Entity\User
        group:                Via\Bundle\CoreBundle\Entity\Group
    profile:
        form:
            type:                 sonata_user_profile
            handler:              sonata.user.profile.form.handler.default
            name:                 sonata_user_profile_form
            validation_groups:
                # Defaults:
                - Profile
                - Default
    admin:                  # Admin Classes
        user:
            #class:           
            #Via\Bundle\CoreBundle\Admin\UserAdmin
            controller:     SonataAdminBundle:CRUD
            translation:    SonataUserBundle
            
#security:
    # [...]
    #acl:
        #connection: default